FROM node:16.13.0-alpine
WORKDIR /usr/src/app/acebook_staging/investors-client
COPY package*.json ./
COPY . .

ENV FRAMEWORK_PROVIDER="graphql"
# ENV NEXT_PUBLIC_GRAPHQL_API_ENDPOINT="http://172.16.10.101:6200/graphql"
ENV NEXT_PUBLIC_GRAPHQL_API_ENDPOINT="https://acebook-api-demo.acemcbohol.ph/graphql"
# ENV NEXT_PUBLIC_GRAPHQL_API_ENDPOINT_SUBSCRIPTION_DEV="ws://172.16.10.101:6200/graphql"
ENV NEXT_PUBLIC_GRAPHQL_API_ENDPOINT_SUBSCRIPTION_DEV="wss://acebook-api-demo.acemcbohol.ph/graphql"
ENV NEXT_PUBLIC_PROD_FRONTEND_ENDPOINT="https://acebook-demo.acemcbohol.ph"
ENV NEXT_PUBLIC_FILE_SERVER_PROD="https://acebook-flsrv-demo.acemcbohol.ph/ftp/uploads/"
ENV NEXT_PUBLIC_SITE_URL="https://asm-demo.acemcbohol.ph/"

ENV NEXT_PUBLIC_PROD_INVESTOR_ENDPOINT="https://asm-demo.acemcbohol.ph/"


RUN yarn

RUN yarn build:gql
EXPOSE 3003


CMD ["yarn", "start"]

