###########################################################
# Rename the file extension to ".yaml" (remove "_") to enable
###########################################################

name: Docker Series Builds

on: 
  push:
    branches: [ main ]
    paths:
      - 'api/**'

  

jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: api
  
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: docker build nodejs
      run: |
       docker build ./api -t intjborj/acebookapi:${{ steps.package-version.outputs.current-version}}
    - name: docker push
      run: |
        docker push intjborj/acebookapi:${{ steps.package-version.outputs.current-version}}
       
    
       
